### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by rogenth** [amaelkady/ABAQUS-Tools#1]
Hello, I have been using this tool the last couple of months for some reinforced concrete simulations that involve CDP parameters and it just makes the workflow so much easier. Thank you for all the work!

I was just wondering if it would be possible to publish the source code, as that could help also not only incorporating other models, but also allowing forks that run on other programing languages (E.g. Python). Thanks again.

**Comment by amaelkady** [comment]
I will try to organize the code and make it open-source soon.
