### ISSUE TITLE
Error in CDP Model Input Generator

### ISSUE THREAD

**Issue by FouadW** [amaelkady/ABAQUS-Tools#10]
Dear Dr Ahmed,

Thank you for everything that you are doing.

I tried to download CDP Model Input Generator, but when I'm trying to open it I get this comment: Conversion to logical from string is not possible. Error in => ABAQUS_CDP_Generator.mlapp at line 958
![Screenshot 2023-08-03 141759](https://github.com/amaelkady/ABAQUS-Tools/assets/141337268/8bd8c1f0-e68d-4b48-8572-e71f49570d39)

**Comment by amaelkady** [comment]
@FouadW The error was identified. Please download the updated installer. It should work fine now.

**Comment by Ranumanish** [comment]
from where will we get the updated version as it still showing the same error.

**Comment by amaelkady** [comment]
@Ranumanish The current version is already updated. Please make sure your Windows language is set to English; otherwise error will occur,
