### ISSUE TITLE
Attempting to run ABAQUS_Steel_Installer.exe results in "Application Install was not successful" message,

### ISSUE THREAD

**Issue by SQ-1** [amaelkady/ABAQUS-Tools#13]
Attempting to run the installer for steel installer on windows 11 results in an error message that application install was not successful.
![Application Error](https://github.com/amaelkady/ABAQUS-Tools/assets/73251897/02d3f9e7-803e-4e45-8430-89e2602d33bf)

**Comment by SQ-1** [comment]
Resolved by uninstalling older release first, installing release from 5 months ago (Aug 23), setting regional language settings to English (UK) and then installing latest release (Nov 23). Seems to be working now.

**Comment by EngnrSoul** [comment]
Dear Professor, thank you for providing the tools for generating the CDP and steel materials data. Thanks for your input and making the materials available for the community.

I was able to installed the software successfully but it keeps requesting for user id and password
