### ISSUE TITLE
ABAQUS_Steel_Installer.exe is not installed correctly.

### ISSUE THREAD

**Issue by Alyosat** [amaelkady/ABAQUS-Tools#14]
Hi sir,

Can you check please the ABAQUS_Steel_Installer.exe file, since it has been packaged with Matlab 2024a (which is still pre-release and not stable) it gives an error when installing?
Can you package it with Matlab 2023b if possible, also? Thanks, and regards.

**Comment by amaelkady** [comment]
@Alyosat The installer has been updated yesterday, please re-try

**Comment by Alyosat** [comment]
Hi sir, after installation, it gives this error and not opening.
![error](https://github.com/amaelkady/ABAQUS-Tools/assets/148915740/33ff3b39-b837-4b3f-a478-163d7bc2b3c2)

**Comment by amaelkady** [comment]
@Alyosat thanks for the note. please try again now.

**Comment by Alyosat** [comment]
- Thanks for the effort sir, it worked
