### ISSUE TITLE
Question about using Steel Generator

### ISSUE THREAD

**Issue by Alan-zhang-zhijian** [amaelkady/ABAQUS-Tools#15]
Hello, I'm trying to use a generator to process the test data I have. However, I found that when I inserted the test data, the generator didn't respond at all, nor did I get an error or anything. But I found that it does work when I select the example you uploaded. Can I ask what's going on here? Is it because my file size (4.6MB) is larger than the sample file (17KB)?

**Comment by novariation** [comment]
Having the same issue

**Comment by amaelkady** [comment]
@Alan-zhang-zhijian @novariation please attach your test data file to debug the issue

**Comment by novariation** [comment]
Thank you for your prompt response. I need the data urgently to run my simulation for my thesis, which is due next week. 
I seek your guidance. Thank you. 
[1.6mm_10mm.xlsx](https://github.com/amaelkady/ABAQUS-Tools/files/14365873/1.6mm_10mm.xlsx)
[1.6mm_txt.txt](https://github.com/amaelkady/ABAQUS-Tools/files/14365874/1.6mm_txt.txt)
[10mm_txt.txt](https://github.com/amaelkady/ABAQUS-Tools/files/14365875/10mm_txt.txt)

**Comment by amaelkady** [comment]
@novariation There are multiple issues with the input file:
1) There should be no headers in the file.
2) The data need to be organized as strain stress NOT stress strain
3( The units of strain should not be in %

**Comment by novariation** [comment]
Thank you for getting back to me.
Fixed all 3, still not working.
[10mm updated.txt](https://github.com/amaelkady/ABAQUS-Tools/files/14374219/10mm.updated.txt)
Kindly get back to me soon.

**Comment by amaelkady** [comment]
@novariation issue #3 is not fixed yet

**Comment by Alan-zhang-zhijian** [comment]
> @Alan-zhang-zhijian @novariation please attach your test data file to debug the issue

Hello there,

This is the file that I have for the data
[test1.txt](https://github.com/amaelkady/ABAQUS-Tools/files/14374570/test1.txt)

**Comment by novariation** [comment]
Issue 3: The strain was in percentage, I converted it by multiplying it by 100. Shouldn't that solve the issue?

**Comment by amaelkady** [comment]
@novariation No, to have the strain data in absolute values, you should divide by 100 not multiply by hundered

**Comment by amaelkady** [comment]
@Alan-zhang-zhijian @novariation Please download the new executable and re-install

**Comment by novariation** [comment]
I have divided by 100 and downloaded the new executable. I still need some help as there is no result.
[10mm updated.txt](https://github.com/amaelkady/ABAQUS-Tools/files/14374805/10mm.updated.txt)

**Comment by Alan-zhang-zhijian** [comment]
> @Alan-zhang-zhijian @novariation Please download the new executable and re-install

@amaelkady Thank you so much. Now it can generate properties from curves. However, this time another problem arises. When I try to generate a curve it keeps saying "Please browse for the text file containing the coupon test data first". This problem occurs even if I try to use the sample data you provided.

**Comment by amaelkady** [comment]
@Alan-zhang-zhijian @novariation Please try the executable I just uploaded

**Comment by novariation** [comment]
Unable to download this time, says virus detected in file, sir.

**Comment by Alan-zhang-zhijian** [comment]
> @Alan-zhang-zhijian @novariation Please try the executable I just uploaded

@amaelkady Thank you so much. This time I was able to access the plastic properties. But I found that for some reason, in the file generated for strain-plasticity, when the strain is zero, its plastic stress is greater than the stress in the next row (when the strain is greater than 0). Can you tell me what's going on here?

**Comment by novariation** [comment]
Unfortunately still not working :(

**Comment by amaelkady** [comment]
@Alan-zhang-zhijian try the news exe, this issue should be fixed

**Comment by novariation** [comment]
@amaelkady sir, Is there a fix for this? The data is the same as i provided previously.

**Comment by Alan-zhang-zhijian** [comment]
> @Alan-zhang-zhijian try the news exe, this issue should be fixed

@amaelkady Thank you very much for your help! I have another question here. I think the starting point of plastic stress should be the yield stress. However, the exe shows a yield stress of 533MPa, while the generated text file shows that the plastic stress starts from a stress of 511MPa. Can you tell me what's going on here?
![image](https://github.com/amaelkady/ABAQUS-Tools/assets/85534509/e4a9b272-64d4-4b6c-84c3-33a1d7c2bc16)

**Comment by amaelkady** [comment]
@Alan-zhang-zhijian this is an issue arising from rounding. This should be fixed now.

**Comment by amaelkady** [comment]
@novariation please elaborate on the issue you are encountring

**Comment by Alan-zhang-zhijian** [comment]
> @Alan-zhang-zhijian this is an issue arising from rounding. This should be fixed now.

It works now. Thank you so much for your help!
