### ISSUE TITLE
error Dialog

### ISSUE THREAD

**Issue by Karsaz1367** [amaelkady/ABAQUS-Tools#5]
hello sir 
when I generate the material data I receive an error :

Error Identifier:   MATLAB:ui:NumericEditField:invalidValue
Error Message:      'Value' must be a double scalar within the range of 'Limits'.
--------------------------------------------------
Error Location:
----------------
Line  185 in AbstractNumericComponent.set.Value
Line  184 in ABAQUS_CDP_Generator.Write_CDP_data_files
Line  349 in ABAQUS_CDP_Generator.GenerateMaterialButtonPushed

**Comment by amaelkady** [comment]
It seems that you specified incorrect value for Gf. Acceptable values should be within 0 to 100 N.mm

**Comment by Dean-edu** [comment]
Hi @amaelkady 
When I use the **ABAQUS_CDP_Generator**, I recivie an error "**Concersion to logical from string is not possible. Error in => ABAQUS_CDP_Generator.mlapp at line 958**"

![image](https://github.com/amaelkady/ABAQUS-Tools/assets/37129837/f2818289-6f71-47d5-a593-f5bb7c42c35a)

**Comment by amaelkady** [comment]
@Dean-edu when do you get this error? during installation or when opening the program?

**Comment by Dean-edu** [comment]
Hi @amaelkady 
When opening the **ABAQUS_CDP_Generator**, I recivie this error.
The program cannot run and exits immediately.

**Comment by amaelkady** [comment]
@Dean-edu Is your windows language set to english?

**Comment by Dean-edu** [comment]
@amaelkady 
Yes, all are set to English
I tried reinstalling this tool, but it doesn't work

**Comment by amaelkady** [comment]
@Dean-edu The error was identified. Please download the updated installer. It should work fine now.
