### ISSUE TITLE
Error when Using ABAQUS- Steel Generator 

### ISSUE THREAD

**Issue by Struct123ure** [amaelkady/ABAQUS-Tools#6]
Hi,
I downloaded the latest "ABAQUS_Steel_Installer", but after installing it says "This tool version has expired! Please check GitHub for new release.", see attached. 
![1](https://github.com/amaelkady/ABAQUS-Tools/assets/135362746/af929319-3d71-4e65-92db-5819fa4f3027)

After clicking ok on the first window I have a second window pop up saying "Invalid or deleted object. Error in => ABAQUS_Steek_Generator.mlapp at line 986". 
![2](https://github.com/amaelkady/ABAQUS-Tools/assets/135362746/20e41cdd-46a7-46d4-ae59-a66851112aee)

Any suggestions on what might be wrong? 
Thanks.

**Comment by amaelkady** [comment]
Thank you for reporting the issue. This should be solved now. Please redownload the updated installer.

**Comment by Struct123ure** [comment]
Thank you, issues is fixed everything works.
