### ISSUE TITLE
Help .odb files

### ISSUE THREAD

**Issue by Mxo23** [amaelkady/ABAQUS-Tools#7]
Dear Mr. Ahmed Elkady,

I hope this email finds you well. I am currently preparing for engineering school entrance exams. I recently came across your impressive work on modeling a steel end-plate bolted connection in Abaqus.

I have a keen interest in structural analysis, and your project aligns perfectly with my area of focus. In order to enhance my understanding and gain insights from your expertise, I was wondering if you would be willing to provide me with the job and visualization files related to your modeling work.

I am particularly interested in using the student version of Abaqus to explore and analyze the results as part of my project. Having access to your files would greatly assist me in studying the intricacies of this specific type of connection and help me prepare effectively for the engineering school entrance exams.

I fully understand the value of your work and the effort you have put into it, and I assure you that the files will be used solely for educational purposes and will not be shared with any other individuals or entities. I highly respect your intellectual property rights and will comply with any conditions or limitations you may have regarding the usage of the files.

I genuinely appreciate any assistance you can provide, and I believe that learning from experienced professionals like you will greatly contribute to my knowledge and future career prospects. I look forward to your positive response.

Thank you very much for your time and consideration.

Best regards,

Mxo23

**Comment by amaelkady** [comment]
The .cae files for the tutorial example are publicaly available on the GitHub repository. Those can be run to obtain the solution (.odb files).

**Comment by Mxo23** [comment]
The problem is that i have the student version of abaqus, so it says to me that i cant submit the job because this version of abaqus is limited to 1000 nodes. Its why i asked you the.odb files

**Comment by Mxo23** [comment]
The problem is that i have the student version of abaqus, so it says to me that i cant submit the job because this version of abaqus is limited to 1000 nodes. Its why i asked you the.odb files

Envoyé de mon iPhone

Le 4 juin 2023 à 20:29, Ahmed Elkady ***@***.***> a écrit :

﻿

The .cae files for the tutorial example are publicaly available on the GitHub repository. Those can be run to obtain the solution (.odb files).
