### ISSUE TITLE
.odb files (again)

### ISSUE THREAD

**Issue by Mxo23** [amaelkady/ABAQUS-Tools#8]
The problem is that i have the student version of abaqus, so it says to me that i cant submit the job because this version of abaqus is limited to 1000 nodes. Its why i asked you the.odb files. Sorry for reopening the issue.

**Comment by Mxo23** [comment]
Also, if you have some times, i'd like to talk with you on skype or something else about my project for my engineering school. If you cannot, no problem.

**Comment by amaelkady** [comment]
Unfortunatly, the odb file is unavailable.
For any inquiries, please post any questions you may have on the Youtube channel and I will try to response as soon as possible,

**Comment by Mxo23** [comment]
Oh okay, no problem. I posted a comment on your video #17 tutorial. This is the comment: Hi sir, im Mxo23 from github. My problem is when i submit the job, it says to me that Abaqus Learning edition have a restriction so the nodes are limited to 1000, when i go on mesh -> query -> mesh: the number of nodes is more than 7000, just because of the column. I try to put their size bigger to have less nodes, but it doesnt work. I have always have more than 4000 nodes. Have you an idea to fix it ?
