### ISSUE TITLE
CDP generator issue

### ISSUE THREAD

**Issue by Ranaamasha** [amaelkady/ABAQUS-Tools#9]
dear dr. Ahmed 
thanks for your help and your useful tool and your great helpful youtube videos
I had an issue with cdp generator when I changed the fcu number and tried to generate material the file named data compression damage contains 0,0 only and when I clicked after generation the attached photo shows the problem
![2 elkady](https://github.com/amaelkady/ABAQUS-Tools/assets/137500591/8969627d-c88b-4183-97eb-cc55fae16c27)

**Comment by amaelkady** [comment]
@Ranaamasha thanks for reporting this bug. This visual issue is now fixed. Please re-download/re-install the tool.
For the compression damage file issue, please send a screen shot of the parameters you used.

**Comment by Ranaamasha** [comment]
![elkady 3](https://github.com/amaelkady/ABAQUS-Tools/assets/137500591/8642ba79-cdfa-4f22-b1e9-f3003ffb984f)
![elkady 4](https://github.com/amaelkady/ABAQUS-Tools/assets/137500591/2beb1830-6e9d-4f4d-a534-c243f37d2044)
![elkady5](https://github.com/amaelkady/ABAQUS-Tools/assets/137500591/e99817a0-c5f7-4f75-ac42-18f7da4126aa)
Thanks dr. Ahmed but there is another bugs in the latest versions the first it can't calculate compression damage for fcu above 50 and the others are in the attached pictures when I tried to regenerate for the same parameters it gives me an error file

**Comment by amaelkady** [comment]
@Ranaamasha A new version is uploaded. For now, please use the chinese code for fcu>50mpa.

**Comment by AndrewN91-A** [comment]
Hello, Dr Ahmed
Thanks for your help and effort, but when I tried to use Carr. & Chu 1985 and my input was stress, strain and MOE the result text doesn't show same strain at same stress value.
![13](https://github.com/amaelkady/ABAQUS-Tools/assets/138163362/38d34f1e-66b4-4350-ba67-1af2130c3436)
![12](https://github.com/amaelkady/ABAQUS-Tools/assets/138163362/0653b484-d766-4198-8b34-b79fd11134a4)

**Comment by amaelkady** [comment]
@AndrewN91-A  Please note that this data represnts the plastc strain not the total strain.

**Comment by AndrewN91-A** [comment]
@amaelkady I believe that plastic strain is meant, and I don't have enough data to yield parameters. All I have is ult comp stress and strain at peak stress also MOE

**Comment by AndrewN91-A** [comment]
@amaelkady I mean, I don't have Elastic properties

**Comment by amaelkady** [comment]
@AndrewN91-A Not sure what MOE refers to but as I mentioned above, the generated compression data file (for abaqus input) contains the stress-plastic strain values based on the parameters you defined.

**Comment by AndrewN91-A** [comment]
@amaelkady MOE=Modulus of Elasticity, The problem with the inputs as I said before all I have is Ult. Stress and corresponding strain and plastic strains are required.
Sorry to bother you with my questions.

**Comment by Ranaamasha** [comment]
please, Dr. Ahmed
when we will get the newest version?
![kady](https://github.com/amaelkady/ABAQUS-Tools/assets/137500591/d2983743-0ad8-4854-9739-fdd8a041f51c)

**Comment by amaelkady** [comment]
@Ranaamasha the new release is available now.

**Comment by l-i-n-lin** [comment]
Dr. Hello, how to download the ABAQUS-CDP-Generator-Installer.exe  ?

**Comment by amaelkady** [comment]
@l-i-n-lin go to the tool folder and click the download button

https://github.com/amaelkady/ABAQUS-Tools/blob/main/CDP%20Generator/ABAQUS_CDP_Generator_Installer.exe

![Image](https://github.com/user-attachments/assets/c9dffa67-3cb1-44b4-8426-09096c12cbf7)

**Comment by l-i-n-lin** [comment]
Thanks！

---- Replied Message ----
| From | Ahmed ***@***.***> |
| Date | 02/12/2025 16:56 |
| To | amaelkady/ABAQUS-Tools ***@***.***> |
| Cc | l-i-n-lin ***@***.***>,
Mention ***@***.***> |
| Subject | Re: [amaelkady/ABAQUS-Tools] CDP generator issue (Issue #9) |

@l-i-n-lin go to the tool folder and click the download button

https://github.com/amaelkady/ABAQUS-Tools/blob/main/CDP%20Generator/ABAQUS_CDP_Generator_Installer.exe

image.png (view on web)
